### PR TITLE
Refine initialize_uninitialized_global_variables

### PR DESCRIPTION
**Pull request by frankyjuang**
Use built-in function `tf.report_uninitialized_variables` to get uninitialized variables.

### CODE REVIEW

**Comment by frankyjuang** [comment]
Besides, would it be better if we set `init_all=False` of `model_train` as default?

**Comment by goodfeli** [comment]
@frankyjuang Why did you close this? Did you decide it wasn't a good idea after looking at the output of the tests?

**Comment by npapernot** [comment]
The tests were failing because of the `pep8` checker

**Comment by frankyjuang** [comment]
No, I found that it's not a good idea to use `tf.report_uninitialized_variables` since it requires a VariableScope with `reuse` set to `True`.

**Pull request closed without merging**
