### PR TITLE
created a tutorial applying fgsm to cifar10

### PR DESCRIPTION
**Pull request by paulhendricks**
Despite only training the nnet for 10 epochs, the results are promising. The adversarialy trained CIFAR10 model performs as well as the non-adversarialy trained CIFAR10 model (about 0.47 accuracy after 10 epochs); however, test accuracy on adversarial examples is about 0.11 for the adversarialy trained CIFAR10 model as opposed to a test accuracy of 0.01 for the non-adversarialy trained CIFAR10 model.

If this is useful, definitely let me know! I'd love to implement the other attacks for cifar10 and perhaps refactor.

I'd also love to train the model for longer than 10 epochs. I'll run some additional tests and report the results.

### CODE REVIEW

**Comment by npapernot** [comment]
The low rate on adversarial training was due to an error in the last `model_eval` call, see 252519a

**Comment by npapernot** [comment]
I am now getting 67% accuracy on legitimate inputs and 63% on (FGSM) adversarial inputs after 50 epochs.

I'll merge for now but feel free to create a new PR if you make improvements to this script.

**Comment by goodfeli** [comment]
For future reference, you should write to cleverhans-dev@googlegroups.com before starting a new feature, to make sure no one else is doing the same thing, etc.

**Comment by paulhendricks** [comment]
Thanks for your help fixing this @npapernot!

And I will going forward @goodfeli, thanks!

**Pull request merged**
